### ISSUE TITLE
.

### ISSUE THREAD

**Issue by JoannaKu** [JoannaKu/Ajax3#1]
Mam kilka problemów :( 
1. nie wiem dlaczego na samym dole zostaje mi pusty odstęp
2. nie podoba mi się co się dzieje z przyciskami po naciśnięciu. Próbowałam to zmienić przez :focus ale coś mi nie wychodzi.
3. da radę zrobić tak, żeby przy wyświetlaniu większej ilości krajów jakoś je rozdzielić, bo póki co wyniki są słabo widoczne? muszę to zrobić w js?

**Comment by michal-bootcamp** [comment]
1. ten odstep wynika z tego, ze laczna wysokosc elementow na stronie nie zajmuje calej wysokosci okna. To dobrze znany przypadek i nazywa sie "sticky footer", czyli zeby footer byl na dole strony niezaleznie od wysokosci elementow. Proponuje pokombinowac w ten sposob: https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/
Poza tym wrzucilbym autora do wnetrza footera
2. https://stackoverflow.com/questions/20340138/remove-blue-border-from-css-custom-styled-button-in-chrome
3. mozesz to zrobic np tak:
```
function showCountriesList(resp) {
    countriesList.empty();
    resp.forEach(function(item) {
        $('<li class="country-box">').text('Country: ' + item.name)
          .append($('<ul>')
          .append($('<li>').text('Capital: ' + item.capital))
          .append($('<li>').text('Region: ' + item.region))
          .append($('<li>').text('Languages: ' + item.languages)))
          .appendTo(countriesList);
    });
}
```
zajrzyj w html, ktory Ci sie wygeneruje i bedziesz wiedziala, co z tym zrobic :)

**Comment by michal-bootcamp** [comment]
jest super :)
jeszcze tak na przyszlosc, jesli bedziesz chciala, mozesz zlikwidowac znikanie bordera buttona na hoverze: usun z regul buttona `border-color: ...` i zamiast tego rozwin samo border: `border: 2px solid #f1c40f`
